dist: noble
sudo: false
branches:
  only:
    - master
language: python
jobs:
  include:
    - python: 3.9
      env: TOXENV=py39
    - python: 3.10
      env: TOXENV=py310
    - python: 3.11
      env: TOXENV=py311
    - python: 3.12
      env: TOXENV=py312
    - python: 3.13
      env: TOXENV=py313
    - python: 3.14
      env: TOXENV=py314
install: travis_retry pip install tox
script: tox
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#aspen"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
