[tox]
envlist = py311,py312,py313,py314
skipsdist = True

[testenv]
deps =
    py314: Sphinx
    py314: sphinx-rtd-theme
commands =
    pip install -q -r requirements.txt -r requirements_tests.txt
    python -m pytest tests {posargs}
    python -m flake8 aspen tests
    py314: python -m pytest --doctest-modules aspen
    py314: sphinx-build -b html -d docs/_build/doctrees docs/ docs/_build/html
setenv =
    PYTHONDONTWRITEBYTECODE=true
    ASPEN_DEBUG=on
